### PR TITLE
Allowing for full configuration of redis pool

### PR DESCRIPTION
**Pull request by angelxmoreno**
Addresses #1 and allows full control of the settings passed to `sol-redis-pool`.
All tests pass.

### CODE REVIEW

**Comment by angelxmoreno** [comment]
Please provide feedback prior to merging. I'd like to also update the readme file to reflect the update.

**Comment by Mulkave** [comment]
@angelxmoreno looking great :+1: please notify me once all done to merge.

**Comment by angelxmoreno** [comment]
awesome! I'll move onto the readme file now

**Comment by angelxmoreno** [comment]
kept it simple and linked to the RedisPool settings example. Please merge if you approve.

**Comment by Mulkave** [comment]
@angelxmoreno thanks for the efforts :smile:

**Pull request merged**
